import type { ExportInput, ExportResult } from '../../../shared/exporters/types';
import type { QualifiedName } from '../../../shared/types';
import { getDialect } from './dialect';
import { toClassName } from './naming';
import { buildRelationPairs, relationsByOwner } from './relations';
import { emitEntity, emitImports } from './template';

interface ResolvedOptions {
  dialectId: string;
  singularize: boolean;
  includeImports: boolean;
  emitNullableExplicit: boolean;
}

function resolveOptions(raw: Record<string, unknown>): ResolvedOptions {
  return {
    dialectId: typeof raw.dialect === 'string' ? raw.dialect : 'postgres',
    singularize: typeof raw.singularize === 'boolean' ? raw.singularize : true,
    includeImports: typeof raw.includeImports === 'boolean' ? raw.includeImports : true,
    emitNullableExplicit: typeof raw.emitNullableExplicit === 'boolean' ? raw.emitNullableExplicit : true,
  };
}

export function generateTypeOrm(input: ExportInput): ExportResult {
  const opts = resolveOptions(input.options);
  const dialect = getDialect(opts.dialectId);
  const warnings: string[] = [];

  if (!dialect) {
    return {
      language: 'typescript',
      content: `// Export failed: dialect "${opts.dialectId}" not registered.\n`,
      warnings: [`Unknown dialect "${opts.dialectId}". Falling back is not supported.`],
    };
  }

  const liveTables = new Set<QualifiedName>(input.schema.tables.map((t) => t.name));
  const pairs = buildRelationPairs(input.schema.refs, { singularize: opts.singularize });
  const { byOwner, orphanedRefIds } = relationsByOwner(pairs, liveTables);

  if (orphanedRefIds.size > 0) {
    for (const id of orphanedRefIds) {
      warnings.push(
        `Relation omitted (${id}): one endpoint is outside the export scope. FK column preserved without decorator.`,
      );
    }
  }

  const decoratorsUsed = new Set<string>();
  const tablesSorted = [...input.schema.tables].sort((a, b) => {
    const ac = toClassName(a.name, { singularize: opts.singularize });
    const bc = toClassName(b.name, { singularize: opts.singularize });
    return ac.localeCompare(bc);
  });

  const entityBlocks: string[] = [];
  for (const table of tablesSorted) {
    const rels = byOwner.get(table.name) ?? [];
    const emitted = emitEntity(table, rels, {
      dialect,
      singularize: opts.singularize,
      emitNullableExplicit: opts.emitNullableExplicit,
    });
    for (const d of emitted.decoratorsUsed) decoratorsUsed.add(d);
    warnings.push(...emitted.warnings);
    entityBlocks.push(emitted.source);
  }

  const headerLines: string[] = [];
  headerLines.push('// Generated by dddbml — Export to TypeORM');
  headerLines.push(`// Dialect: ${dialect.label}  ·  Scope: ${input.scope}  ·  Tables: ${tablesSorted.length}`);
  headerLines.push('// Edit freely; re-export will overwrite if you save under the same name.');
  if (opts.includeImports) {
    headerLines.push('');
    headerLines.push(emitImports(decoratorsUsed));
  }

  const content = headerLines.join('\n') + '\n\n' + entityBlocks.join('\n\n') + '\n';

  return {
    language: 'typescript',
    content,
    warnings: warnings.length > 0 ? warnings : undefined,
  };
}
